### PR TITLE
Iubenda

### PR DESCRIPTION
**Pull request by rondey**
Hi, I've made this changes: possibility to set the width and height dimensions and make this project compatible with Iubenda(block the video until the user accept the cookies and privacy policy)

### CODE REVIEW

**Comment by felixgirault** [comment]
Hi,

it's a good thing to be able to set width and height on the iframe.
I might refactor it slightly to be more flexible before merging.

Could you tell me more about Iubenda ? I don't know much about it and I'm not sure if it would need to be integrated to the core.

**Comment by felixgirault** [comment]
I pushed some code on the feature-template branch that I think could solve your problem : https://github.com/felixgirault/multiplayer/blob/feature-template/lib/Multiplayer/Multiplayer.php

With the new way of building HTML code you could do : 

``` php
echo $Multiplayer->html('http://foo.bar', [], function($url) {
    return '<iframe class="_iub_cs_activate" src="suppressed" width="800" height="600" />';
});
```

**Comment by rondey** [comment]
Hi,I like very much the template feature. Good job!
Iubenda is a solution that allow the website to comply the European Cookie Law: users are informed about the cookies website's and the tracking plugins(like the Facebook Like Box or the iframe containing videos from YouTube or Vimeo). Iubenda block cookies and tracking plugins before user accept (as required by Italian Law - Garante della Privacy dispositions).

**Comment by rondey** [comment]
Hi,I like very much the template feature. Good job!
Iubenda is a solution that allow the website to comply the European Cookie Law: users are informed about the cookies website's and the tracking plugins(like the Facebook Like Box or the iframe containing videos from YouTube or Vimeo). Iubenda block cookies and tracking plugins before user accept (as required by Italian Law - Garante della Privacy dispositions).

Sorry for the closed and reopened pull request, i'm a newbie.

**Comment by felixgirault** [comment]
Thanks :)
I'm merging the template branch and tagging a new version.
I hope it will cover your needs!

**Pull request closed without merging**
